# Permalinks

# Setup
title: Geordie Kidd
description: Personal website of Geordie Kidd
url: https://geordiekidd.github.io
baseurl: ""

# About/contact
author:
  name: Geordie Kidd
  url: https://geordiekidd.github.io
  email: geordiekidd@gmail.com

# Build settings
markdown: kramdown

# The default sharing image for sharing any page to social media. If a post has
# a "sharing_image" meta that will be used instead
# Use a relative path from the root of the project!
# sharing_image: /assets/sharing_image.png
